In [1]:
pwd

'/Users/shivaborusu/ML_PRACTICE'

In [2]:
mkdir EDA

In [3]:
cd EDA

/Users/shivaborusu/ML_PRACTICE/EDA


In [4]:
from sklearn.svm import SVR

In [ ]:
svr = SVR()

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.random.randn(10)

array([-0.3331027 , -0.81148481, -0.4127746 ,  0.14207226, -1.54203238,
        0.35490509,  1.45402025, -1.14878318, -0.14239963,  0.4980095 ])

In [12]:
np.linspace(1,19,10)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [13]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}

In [15]:
df = pd.DataFrame(d)

In [16]:
df

Name  Age  Rating
0      Tom   25    4.23
1    James   26    3.24
2    Ricky   25    3.98
3      Vin   23    2.56
4    Steve   30    3.20
5    Smith   29    4.60
6     Jack   23    3.80
7      Lee   34    3.78
8    David   40    2.98
9   Gasper   30    4.80
10  Betina   51    4.10
11  Andres   46    3.65

In [32]:
df['Rating'].max()

4.8

In [33]:
df['new'] = df['Rating'].apply(lambda x: x*x)

In [56]:
df.sort_values('Rating')

Name  Age  Rating      new
3      Vin   23    2.56   6.5536
8    David   40    2.98   8.8804
4    Steve   30    3.20  10.2400
1    James   26    3.24  10.4976
11  Andres   46    3.65  13.3225
7      Lee   34    3.78  14.2884
6     Jack   23    3.80  14.4400
2    Ricky   25    3.98  15.8404
10  Betina   51    4.10  16.8100
0      Tom   25    4.23  17.8929
5    Smith   29    4.60  21.1600
9   Gasper   30    4.80  23.0400

In [1]:
df.groupby('Age').sum()['Rating']

NameError: name 'df' is not defined

In [54]:
df['Age'].unique()

array([25, 26, 23, 30, 29, 34, 40, 51, 46])

In [45]:
2.56+3.80

6.359999999999999

In [7]:
type(set({}))

set

In [3]:
type(())

tuple

In [2]:
import pandas as pd

In [18]:
df1 = pd.DataFrame({'Name': ["Shiva", "Kotesh"], 'Number': [1,2]})

In [24]:
df1

Name  Number
0   Shiva       1
1  Kotesh       2

In [21]:
df2 = pd.read_csv?

In [ ]:
df2 = pd.read_csv

In [35]:
df1.loc[0:]['Name']

0     Shiva
1    Kotesh
Name: Name, dtype: object

In [37]:
df1.Name

0     Shiva
1    Kotesh
Name: Name, dtype: object

In [54]:
from flask import Flask

In [55]:
app = Flask(__name__)

In [57]:
@app.route('/home')
def home():
    return "Hello world!"

In [62]:
if __name__ == "__main__":
    app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [17/Jun/2020 00:15:11] "GET /home HTTP/1.1" 200 -


In [63]:
import numpy as np

In [66]:
a = np.array([[1,2,3], [4,5,6]])

In [67]:
a

array([[1, 2, 3],
       [4, 5, 6]])